### ISSUE TITLE
Missing S/MIME signed email verification indicators

### ISSUE THREAD

**Issue by apparition47** [apparition47/MailTrackerBlockerApp#15]
>Not compatible with Sonoma Mail digital signature and encryption feature, which I use with the apporpriate certificates.

Expected:
![Screenshot 2024-05-26 at 10 08 25 PM](https://github.com/apparition47/MailTrackerBlockerApp/assets/3298414/83d6a021-175e-4949-bcb5-29b52a5d19f1)

Actual:
![Screenshot 2024-05-26 at 10 07 56 PM](https://github.com/apparition47/MailTrackerBlockerApp/assets/3298414/f86cbccf-6324-492c-86cf-99879e45a5f6)

When viewing signed emails, the `Signed` label isn't displayed with the MailTrackerBlocker message security extension. Also the signing/encryption icons are greyed out in the message composer. Tested with [Actalis' free S/MIME cert](https://extrassl.actalis.it/portal/uapub/freemail?lang=en).

```
Content-Type: multipart/signed;
	boundary="Apple-Mail=_CB35ED7D-E91E-4556-85DF-1AFDCCA86A12";
	protocol="application/pkcs7-signature";
	micalg=sha-256
Mime-Version: 1.0 (Mac OS X Mail 16.0 \(3774.600.62\))
Subject: signed test
```

```
--Apple-Mail=_CB35ED7D-E91E-4556-85DF-1AFDCCA86A12
Content-Disposition: attachment;
	filename=smime.p7s
Content-Type: application/pkcs7-signature;
	name=smime.p7s
Content-Transfer-Encoding: base64
```

**Comment by apparition47** [comment]
Implemented the "Signed" indicator when viewing messages in 1.1.6.

Composing emails with signing and/or encryption is yet to be implemented. For now, you'll need to disable the MailTrackerBlocker extension if you need to send signed or encrypted emails.

**Comment by irodknocker1** [comment]
> Implemented the "Signed" indicator when viewing messages in 1.1.6.
> 
> Composing emails with signing and/or encryption is yet to be implemented. For now, you'll need to disable the MailTrackerBlocker extension if you need to send signed or encrypted emails.

or use the Lite extension in the meantime :)

**Comment by apparition47** [comment]
@irodknocker1 Absolutely. Thanks for pointing that out.

Screenshot for reference: ![](https://private-user-images.githubusercontent.com/3298414/368420956-7dea6b36-1d48-4ec8-af31-40ded347d768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzIwNTksIm5iZiI6MTcyNjczMTc1OSwicGF0aCI6Ii8zMjk4NDE0LzM2ODQyMDk1Ni03ZGVhNmIzNi0xZDQ4LTRlYzgtYWYzMS00MGRlZDM0N2Q3NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMDc0MjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTgwOTM4MTczOWQ2YjA3NjcyOGIyZDk1OGJhNjc4YWIyNjkxMWI1MTMzMjA1YjEzNDA1NzI2ODdjMzQzNGE0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PQA7DfWbQti5IhsjvENowXk-n4DnsxniiuYswC6YtsM)

**Comment by irodknocker1** [comment]
@apparition47 After almost 2 years this is still not fixed. Do you think you can fix it soon?

**Comment by apparition47** [comment]
@irodknocker1 Have you tried 1.2? It was released yesterday

**Comment by irodknocker1** [comment]
Yes, but unfortunately it still doesn’t work.

**Comment by apparition47** [comment]
@irodknocker1 1.2 was supposed to support S/MIME but looks like sending any signed/encrypted emails was completely broken. This should be fixed in 1.2.1 which should be live after App Store review. Tested it Actalis certs.

**Comment by apparition47** [comment]
Released 1.2.1

**Comment by irodknocker1** [comment]
Sorry, it is still not working with 1.2.1

I have a certificate from Sectigo.

**Comment by apparition47** [comment]
What is the error or problem you're seeing? Is it when you're sending or receiving? Are you signing and/or encrypting emails?

**Comment by irodknocker1** [comment]
Signing. Then it simply stops working. The icon for signing is also greyed out and can no longer be clicked.

<img width="348" height="198" alt="Image" src="https://github.com/user-attachments/assets/3ed0d1fe-e864-4e57-bb58-38a1e90ced29" />

**Comment by apparition47** [comment]
I'll have to improve the UI but could you try tapping the 🛡️ icon and toggling the S/MIME switch then seeing if you can enable signing afterward? MailTrackerBlocker should prompt you for Keychain access after (which is needed to access your certificate)

<img width="520" height="209" alt="Image" src="https://github.com/user-attachments/assets/05d616b0-2ade-4f69-a20a-e9539e60cd9f" />

**Comment by irodknocker1** [comment]
Oh, thanks. It works now.
Yes, you should make that a bit more visible. I would never have thought of that.

**Comment by apparition47** [comment]
Improved in 1.2.2 to auto-enable once tapping the sign/encrypt icons

**Comment by weekijoon** [comment]
I think this might not be fully resolved when viewing signed emails **with attachments.** When viewing signed email with an attachment, Mail shows a mismatch of digital signature and blocks out the entire message (even though the ⓧ label says valid certificate). Emails without attachments works as intended. 

Using the lite extension or turning off the extension shows the same signed email with attachment as normal (with valid signatures, no mail error banner).

Tested on: 1.2.2, with signed emails in the sent folders
Expected: 
<img width="260" height="56" alt="Image" src="https://github.com/user-attachments/assets/e1726b5f-ccf7-4a6b-97c1-50eb85634a1f" />

Actual:
<img width="1752" height="180" alt="Image" src="https://github.com/user-attachments/assets/313d74af-2fe6-46cb-aed3-b757e07bca7d" />
Clicking "Show details":
<img width="246" height="185" alt="Image" src="https://github.com/user-attachments/assets/5a97b082-f349-440b-8875-01a4bdce2b58" />

**Comment by apparition47** [comment]
Thanks @weekijoon for reporting that; haven't previously tested attachments (`signed/multipart`). I think I have it fixed in 1.2.4 which should be available after App Store review
